name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your branch name if you're using something other than main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # You can change the version if needed

      - name: Install dependencies
        run: |
          npm install
      
      - name: Build project with Vite
        run: |
          npm run build  # This will create the dist folder
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # The directory with the built files
